<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

$now = time();

require_once(JPATH_COMPONENT_SITE . DS . 'helpers' . DS . 'simple-gmap-api' . DS . "simpleGMapAPI.php");
require_once(JPATH_COMPONENT_SITE . DS . 'helpers' . DS . 'simple-gmap-api' . DS . "simpleGMapGeocoder.php");

$map = new simpleGMapAPI();
$geo = new simpleGMapGeocoder();

$map->setWidth(400);
$map->setHeight(400);
$map->setBackgroundColor('#d0d0d0');
$map->setMapDraggable(true);
$map->setDoubleclickZoom(false);
$map->setScrollwheelZoom(true);

$map->showDefaultUI(false);
$map->showMapTypeControl(true, 'DROPDOWN_MENU');
$map->showNavigationControl(true, 'DEFAULT');
$map->showScaleControl(true);
$map->showStreetViewControl(true);

$map->setZoomLevel(10); // not really needed because showMap is called in this demo with auto zoom
$map->setInfoWindowBehaviour('SINGLE_CLOSE_ON_MAPCLICK');
$map->setInfoWindowTrigger('CLICK');

//$map->addMarkerByAddress("Toronto, NY");
//$map->addMarkerByAddress("Bloomfield, NY");
//$map->addMarkerByAddress("Gramacy, NY");

//get geocode
$geo_1 = $geo->getGeoCoords("Harrison, NY");
$geo_2 = $geo->getGeoCoords("Mamaroneck, NY");


//$map->addMarkerByAddress("Bronx, NewYork", "Universität Bielefeld", "<a href=\"http://www.uni-bielefeld.de\" target=\"_blank\">http://www.uni-bielefeld.de</a>", "");
//$map->addMarker(52.0149436, 8.5275128, "Sparrenburg Bielefeld", "Sparrenburg, 33602 Bielefeld, Deutschland<br /><img src=\"http://www.bielefeld.de/ftp/bilder/sehenswuerdigkeiten/sehenswuerdigkeiten/sparrenburg-bielefeld-435.gif\"", "http://google-maps-icons.googlecode.com/files/museum-archeological.png");


//$map->addMarker(52.0149436, 8.5275128, "Sparrenburg Bielefeld", "Sparrenburg, 33602 Bielefeld, Deutschland<br /><img src=\"http://www.bielefeld.de/ftp/bilder/sehenswuerdigkeiten/sehenswuerdigkeiten/sparrenburg-bielefeld-435.gif\"", "http://google-maps-icons.googlecode.com/files/museum-archeological.png");

$opts = array('fillColor'=>'#0000dd', 'fillOpacity'=>0.2, 'strokeColor'=>'#A6A1C4', 'strokeOpacity'=>1, 'strokeWeight'=>1, 'clickable'=>true);
$map->addCircle($geo_1['lat'], $geo_1['lng'], 2000, "Test 1", $opts);

$map->addCircle($geo_2['lat'], $geo_2['lng'], 2000, "Test 2", $opts);

?>

<div id="list-items">
	<ul class="items">
		<?php 
		foreach($this->items as $item): 
			$aboutTime = ( $now - strtotime($item->created) ) / (24 * 60 * 60);
		
			if ($aboutTime < 1)
				$time = round($aboutTime * 60) . ' hours';
			else
				$time = round($aboutTime) . ' days';
			
			//get defautl images
			$images = @unserialize($item->images);
			
			$defaultImage = '';
			
			if (is_array($images))
				$defaultImage = $images[0];
			
			$Itemid = JRequest::getInt('Itemid');
		?>
		<li>
		<a href="<?php echo JRoute::_('index.php?option=com_rental&view=apartment&id=' . (int) $item->id . '&Itemid=' . $Itemid); ?>">
			<?php echo $this->escape($item->bedrooms) . ', ' . $this->escape($item->retal_location_title) . ', $' . $this->escape($item->price); ?>
		</a>		
		<br>
		Time on site: <?php echo $time; ?>
		<br>
		Agent: <?php echo $item->agent; ?>
		<br>
		
		<?php if ($defaultImage): ?>
		<img src="images/com_rental/upload/<?php echo $defaultImage['image']; ?>" width="100" />
		<?php endif; ?>
		
		<div class="clr" style="clear: both;"></div>
		
		</li>
		<?php endforeach; ?>
	</ul>
	
	<div id="float-gmap">
		<?php
		$map->printGMapsJS();
		
		// showMap with auto zoom enabled
		$map->showMap(true);
		?>
	</div>
	
	<div class="pagination">
		<?php echo $this->pagination->getPagesLinks(); ?>
	</div>

</div>