<?php
/**
 * @version		$Id: edit.php $
 * @package		Joomla.Administrator
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers/html');
JHtml::_('behavior.tooltip');
JHtml::_('behavior.formvalidation');
?>
<script type="text/javascript">
	Joomla.submitbutton = function(task)
	{
		if (task == 'apartment.cancel' || document.formvalidator.isValid(document.id('apartment-form'))) {
			Joomla.submitform(task, document.getElementById('apartment-form'));
		}
	}
</script>

<form action="<?php echo JRoute::_('index.php?option=com_rental&layout=edit&id='.(int) $this->item->id); ?>" method="post" name="adminForm" id="apartment-form" class="form-validate" enctype="multipart/form-data">
	<div class="width-60 fltlft">
		<fieldset class="adminform">
			<legend><?php echo empty($this->item->id) ? JText::_('COM_RENTAL_NEW_APARTMENT') : JText::sprintf('COM_RENTAL_APARTMENT_DETAILS', $this->item->id); ?></legend>
			<ul class="adminformlist">
				
				<?php /*
				<li><?php echo $this->form->getLabel('title'); ?>
				<?php echo $this->form->getInput('title'); ?></li>
				
				<li><?php echo $this->form->getLabel('alias'); ?>
				<?php echo $this->form->getInput('alias'); ?></li>
				*/ ?>
				<li><?php echo $this->form->getLabel('location_id'); ?>
				<?php echo $this->form->getInput('location_id'); ?></li>
				
				<li><?php echo $this->form->getLabel('agent_id'); ?>
				<?php echo $this->form->getInput('agent_id'); ?></li>
				
				<li><?php echo $this->form->getLabel('price'); ?>
				<?php echo $this->form->getInput('price'); ?></li>		
				
				<li><?php echo $this->form->getLabel('bedrooms'); ?>
				<?php echo $this->form->getInput('bedrooms'); ?></li>
				
				<li><?php echo $this->form->getLabel('bathrooms'); ?>
				<?php echo $this->form->getInput('bathrooms'); ?></li>
				
				<li><?php echo $this->form->getLabel('square_ft'); ?>
				<?php echo $this->form->getInput('square_ft'); ?></li>
				
				<li><?php echo $this->form->getLabel('listed_for'); ?>
				<?php echo $this->form->getInput('listed_for'); ?></li>
				
				<li><?php echo $this->form->getLabel('available_on'); ?>
				<?php echo $this->form->getInput('available_on'); ?></li>
				
				<li><?php echo $this->form->getLabel('pets'); ?>
				<?php echo $this->form->getInput('pets'); ?></li>
				
				<li><?php echo $this->form->getLabel('address'); ?>
				<?php echo $this->form->getInput('address'); ?></li>
				
				<li><?php echo $this->form->getLabel('address_2'); ?>
				<?php echo $this->form->getInput('address_2'); ?></li>
				
				<li><?php echo $this->form->getLabel('city'); ?>
				<?php echo $this->form->getInput('city'); ?></li>
				
				<li><?php echo $this->form->getLabel('portal_code'); ?>
				<?php echo $this->form->getInput('portal_code'); ?></li>
				
				<li><?php echo $this->form->getLabel('country'); ?>
				<?php echo $this->form->getInput('country'); ?></li>
				
						
				
				<li><?php echo $this->form->getLabel('state'); ?>
				<?php echo $this->form->getInput('state'); ?></li>

				<li><?php echo $this->form->getLabel('id'); ?>
				<?php echo $this->form->getInput('id'); ?></li>
			</ul>
			<div class="clr"> </div>
			<?php echo $this->form->getLabel('description'); ?>
			<div class="clr"> </div>
			<?php echo $this->form->getInput('description'); ?>
			<div class="clr"> </div>

		</fieldset>
	</div>

<div class="width-40 fltrt">
	<?php echo JHtml::_('sliders.start','apartment-sliders-'.$this->item->id, array('useCookie'=>1)); ?>

	<?php echo JHtml::_('sliders.panel',JText::_('COM_RENTAL_GROUP_LABEL_PUBLISHING_DETAILS'), 'publishing-details'); ?>
		<fieldset class="panelform">
		<ul class="adminformlist">
			<?php foreach($this->form->getFieldset('publish') as $field): ?>
				<li><?php echo $field->label; ?>
					<?php echo $field->input; ?></li>
			<?php endforeach; ?>
			</ul>
		</fieldset>

	<?php echo JHtml::_('sliders.panel',JText::_('JGLOBAL_FIELDSET_METADATA_OPTIONS'), 'metadata'); ?>
		<fieldset class="panelform">
			<ul class="adminformlist">
				<?php foreach($this->form->getFieldset('metadata') as $field): ?>
					<li><?php echo $field->label; ?>
						<?php echo $field->input; ?></li>
				<?php endforeach; ?>
			</ul>
		</fieldset>

	<?php echo JHtml::_('sliders.end'); ?>
	<input type="hidden" name="task" value="" />
	<?php echo JHtml::_('form.token'); ?>
</div>

<div class="clr"></div>
</form>
