<?php
/**
 * @version		$Id: rental.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

// Include dependancies
jimport('joomla.application.component.controller');

// domain: gorent.com
$params = &JComponentHelper::getParams( 'com_rental' );

//define('CFG_FACEBOOK_API_ID', '419646791426412');
//define('CFG_FACEBOOK_API_SECRET', 'a7fb30ef35a96ece5e0f95e15878069b');

define('CFG_FACEBOOK_API_ID', $params->get('cfg_fb_api_id'));
define('CFG_FACEBOOK_API_SECRET', $params->get('cfg_fb_api_secret'));

// print_r($params);

//require util class
require_once JPATH_COMPONENT_ADMINISTRATOR . DS . 'helpers/util.class.php';

$controller = JController::getInstance('Rental');
$controller->execute(JRequest::getCmd('task'));
$controller->redirect();
