<?php
/**
 * @version		$Id: rental.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

// Include dependancies
jimport('joomla.application.component.controller');

//require util class
require_once JPATH_COMPONENT_ADMINISTRATOR . DS . 'helpers/util.class.php';

$controller = JController::getInstance('Rental');
$controller->execute(JRequest::getCmd('task'));
$controller->redirect();
