<?php
/**
 * @version		$Id: images.php $
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */
 
/**
 Generate by Component Gen Code - 2012
 */

defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');

/**
 * Methods supporting a list of Images records.
 *
 * @package		Joomla.Administrator
 * @subpackage	com_rental
 * @since		1.6
 */
class RentalModelImages extends JModelList
{
	/**
	 * Constructor.
	 *
	 * @param	array	An optional associative array of configuration settings.
	 * @see		JController
	 * @since	1.6
	 */
	public function __construct($config = array())
	{
		if (empty($config['filter_fields'])) {
			$config['filter_fields'] = array(
				'id', '#__retal_apartment_images.id',
				'state', '#__retal_apartment_images.state',
				'title', '#__retal_apartment_images.title', 'alias', '#__retal_apartment_images.alias', 'images', '#__retal_apartment_images.images'
			);
		}

		parent::__construct($config);
	}
	
	
	
	#FUNCTION_GET_AUTHOR#

	/**
	 * Build an SQL query to load the list data.
	 *
	 * @return	JDatabaseQuery
	 * @since	1.6
	 */
	protected function getListQuery()
	{
		// Initialise variables.
		$db		= $this->getDbo();
		$query	= $db->getQuery(true);

		// Select the required fields from the table.
		$query->select(
			$this->getState(
				'list.select',
				'#__retal_apartment_images.id, #__retal_apartment_images.state, #__retal_apartment_images.checked_out AS checked_out, #__retal_apartment_images.checked_out_time AS checked_out_time, 
				#__retal_apartment_images.publish_up, #__retal_apartment_images.publish_down, #__retal_apartment_images.ordering
				, #__retal_apartment_images.title, #__retal_apartment_images.alias, #__retal_apartment_images.images'
			)
		);
		$query->from('`#__retal_apartment_images`');

		// Join over the users for the checked out user.
		$query->select('uc.name AS editor');
		$query->join('LEFT', '#__users AS uc ON uc.id=#__retal_apartment_images.checked_out');
		
		// Join over the rental_apartments
$query->select('rental_apartments_0.title AS rental_apartments_0_title, rental_apartments_0.bedrooms AS rental_apartments_0_bedrooms');
$query->join('INNER', '#__rental_apartments AS rental_apartments_0 ON rental_apartments_0.id = #__retal_apartment_images.apartment_id');


		
		
		
		// Filter by search
						$search = $this->getState('filter.search');
						if (!empty($search))
						{							
							$searchLike = $db->Quote('%'.$db->getEscaped($search, true).'%');
							$search = $db->Quote($db->getEscaped($search, true));
						$query->where('(#__retal_apartment_images. = '.$search.')');
							} //end search
		
		// Add the list ordering clause.
		$orderCol	= $this->state->get('list.ordering');
		$orderDirn	= $this->state->get('list.direction');
		
		$query->order($db->getEscaped($orderCol.' '.$orderDirn));

		//echo nl2br(str_replace('#__','jos_',$query));
		return $query;
	}

	/**
	 * Returns a reference to the a Table object, always creating it.
	 *
	 * @param	type	The table type to instantiate
	 * @param	string	A prefix for the table class name. Optional.
	 * @param	array	Configuration array for model. Optional.
	 * @return	JTable	A database object
	 * @since	1.6
	 */
	public function getTable($type = 'Images', $prefix = 'RentalTable', $config = array())
	{
		return JTable::getInstance($type, $prefix, $config);
	}

	/**
	 * Method to auto-populate the model state.
	 *
	 * Note. Calling getState in this method will result in recursion.
	 *
	 * @since	1.6
	 */
	protected function populateState($ordering = null, $direction = null)
	{
		// Initialise variables.
		$app = JFactory::getApplication('administrator');

		// Load the filter state.
		$search = $this->getUserStateFromRequest($this->context.'.filter.search', 'filter_search');
							$this->setState('filter.search', $search);
		
		#SET_FILTER_STATE_STATE#
		
		
		
		
		
		

		// List state information.
		parent::populateState('#__retal_apartment_images.id', 'DESC');
	}
}