<?php
/**
 * @version		$Id: rentalcustomuserid.php $
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

defined('JPATH_BASE') or die;

jimport('joomla.html.html');
jimport('joomla.form.formfield');
jimport('joomla.form.helper');
JFormHelper::loadFieldClass('list');

/**
 * Custom Field class for the Joomla Framework.
 *
 * @package		Joomla.Administrator
 * @subpackage	com_rental
 * @since		1.6
 */
class JFormFieldAmenities extends JFormFieldList
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since	1.6
	 */
	protected $type = 'Amenities';

	/**
	 * Method to get the field options.
	 *
	 * @return	array	The field option objects.
	 * @since	1.6
	 */
	public function getOptions()
	{
		// Initialize variables.
		$options = array();

		$db		= JFactory::getDbo();
		$query	= $db->getQuery(true);
		
		$query->select('id As value, title As text');
		$query->from('#__rental_amenities AS a');
		$query->where('a.state = 1');

		// Get the options.
		$db->setQuery($query);
		
		$options = $db->loadObjectList();
		
		if ($db->getErrorMsg())
			die($db->getErrorMsg());

		return $options;
	}
	
	public function getInput()
	{
		$html = '<ul style="float: left; width: 360px;">';
		
		$options = self::getOptions();
		
		//get list checkbox
		foreach ($options as $option)
		{
			$checked = (in_array($option->value, $this->value)) ? 'checked="checked"' : '';
			
			$html .= '<li style="float: left; width: 120px; line-height: 23px;">
						<input type="checkbox" name="'.$this->name.'[]" value="'.$option->value.'" '.$checked.' /> ' . $option->text . 
					'</li>';
		}
		
		$html .= '</ul>';
		
		return $html;
	}
}
