<?php
/**
 * @version		$Id: rentalcustomuserid.php $
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

defined('JPATH_BASE') or die;

jimport('joomla.html.html');
jimport('joomla.form.formfield');
jimport('joomla.form.helper');
JFormHelper::loadFieldClass('list');

/**
 * Custom Field class for the Joomla Framework.
 *
 * @package		Joomla.Administrator
 * @subpackage	com_rental
 * @since		1.6
 */
class JFormFieldBrokerEntityType extends JFormFieldList
{
	
	public function getInput()
	{
		$html = '<div style="float: left;">';
		
		$html .= '<fieldset id="jform_months_per_billing_cycle" class="radio inputbox">
				<input type="radio" value="1" name="jform[entity_type]" id="broker_entity_type_1" checked="checked"> <label>Broker/salesperson</label>
				<input type="radio" value="2" name="jform[entity_type]" id="broker_entity_type_2"> <label>Landlord</label>
				<input type="radio" value="3" name="jform[entity_type]" id="broker_entity_type_3"> <label>Management company</label>
				</fieldset>';
		
		$html .= '</div>';
		
		return $html;
	}
	
	private function _getAgentInfo($agentId)
	{
		
	}
}
