<?php
/**
 * @version		$Id: rentalcustomagentid.php $
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

defined('JPATH_BASE') or die;

jimport('joomla.html.html');
jimport('joomla.form.formfield');
jimport('joomla.form.helper');
JFormHelper::loadFieldClass('list');

/**
 * Custom Field class for the Joomla Framework.
 *
 * @package		Joomla.Administrator
 * @subpackage	com_rental
 * @since		1.6
 */
class JFormFieldCreditScores extends JFormFieldList
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since	1.6
	 */
	protected $type = 'CreditScores';

	/**
	 * Method to get the field options.
	 *
	 * @return	array	The field option objects.
	 * @since	1.6
	 */
	public function getOptions()
	{
		// Initialize variables.
		$options = array();
		
		$arr = JEUtil::getCreditScore();
		
		foreach ($arr as $key => $score)
		{
			$option = new stdClass();
			$option->value = $key;
			$option->text = $score[0] . ' ' . $score[1] ;
			
			$options[] = $option;
		}

		array_unshift($options, JHtml::_('select.option', '', JText::_('COM_RENTAL_SELECT')));

		return $options;
	}
}
