<?php
/**
 * @version		$Id: rentalcustomlocationid.php $
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

defined('JPATH_BASE') or die;

jimport('joomla.html.html');
jimport('joomla.form.formfield');
jimport('joomla.form.helper');
JFormHelper::loadFieldClass('list');

/**
 * Custom Field class for the Joomla Framework.
 *
 * @package		Joomla.Administrator
 * @subpackage	com_rental
 * @since		1.6
 */
class JFormFieldNeighborhoods extends JFormFieldList
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since	1.6
	 */
	protected $type = 'Neighborhoods';

	/**
	 * Method to get the field options.
	 *
	 * @return	array	The field option objects.
	 * @since	1.6
	 */
	public function getCategories()
	{
		// Initialize variables.
		$options = array();

		$db		= JFactory::getDbo();
		$query	= $db->getQuery(true);
		
		$query->select('*')
				->from('#__categories')
				->where('extension = "com_rental"')
				->where('parent_id = 1')
			;
		
		$db->setQuery($query);
		
		$categories = $db->loadObjectList();
		
		// Check for a database error.
		if ($db->getErrorNum()) {
			JError::raiseWarning(500, $db->getErrorMsg());
		}
		
		foreach ($categories as & $cate)
		{
			$query	= $db->getQuery(true);
			
			$query->select('id As value, title As text')
					->from('#__retal_location AS a')
					->where('a.state = 1')
					->where('catid = ' . (int) $cate->id . ' OR catid IN (SELECT id FROM #__categories WHERE parent_id = '. (int) $cate->id .')')
					->order('a.title');
			
			// Get the options.
			$db->setQuery($query);

			$options = $db->loadObjectList();
			
			// Check for a database error.
			if ($db->getErrorNum()) {
				JError::raiseWarning(500, $db->getErrorMsg());
			}
			
			$cate->options = $options;
		}

		return $categories;
	}
	
	public function getInput() 
	{
		if (!is_array($this->value))
			$value = unserialize($this->value);
		else
			$value = $this->value;
		
		$categories = $this->getCategories();
		
		$html = '<div id="neighborhoods_id">';
		
		$html .= '<div>';
		foreach ($categories as $cate)
		{
			$html .= '<span>'.$cate->title.'</span>';
		}
		$html .= '</div>';
		
		foreach ($categories as $cate)
		{
			$html .= '<ul>';
			
			foreach ($cate->options as $option)
			{
				$checked = (in_array($option->value, $value)) ? 'checked="checked"' : '';
				
				$html .= '<span><input type="checkbox"  name="'.$this->name.'[]" value="'.$option->value.'" ' . $checked . '>' . $option->text . '</span>';
			}
			
			$html .= '</ul>';
		}
		
		$html .= '</div>';
		
		return $html;
	}
}
