<?php
/**
 * @version		$Id: rentalcustomuserid.php $
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

defined('JPATH_BASE') or die;

jimport('joomla.html.html');
jimport('joomla.form.formfield');
jimport('joomla.form.helper');
JFormHelper::loadFieldClass('list');

/**
 * Custom Field class for the Joomla Framework.
 *
 * @package		Joomla.Administrator
 * @subpackage	com_rental
 * @since		1.6
 */
class JFormFieldPetAllow extends JFormFieldList
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since	1.6
	 */
	protected $type = 'PetAllow';

	/**
	 * Method to get the field options.
	 *
	 * @return	array	The field option objects.
	 * @since	1.6
	 */
	public function getOptions()
	{
		// Initialize variables.
		$options = array();

		$arrPetAllow = JEUtil::getPetAllow();
		
		foreach ($arrPetAllow as $key => $allow)
		{
			$option = new stdClass();
			$option->value = $key;
			$option->text = $allow;
			
			$options[] = $option;
		}

		return $options;
	}
	
	public function getInput()
	{
		$html = '<ul style="float: left; width: 400px;">';
		
		$options = self::getOptions();
		
		$value = array();
		
		if ($this->value)
			$value = explode(',', $this->value);
		
		//get list checkbox
		foreach ($options as $option)
		{
			
			$checked = (in_array($option->value, $value)) ? 'checked="checked"' : '';
			
			$html .= '<li style="float: left; width: 195px; line-height: 23px;">
						<input id="pets_'.$option->value.'" type="checkbox" name="'.$this->name.'[]" value="'.$option->value.'" '.$checked.' /> ' . $option->text . 
					'</li>';
		}
		
		$html .= '</ul>';
		
		return $html;
	}
}
?>

<script type="text/javascript">
<!--
	window.addEvent('domready', function(){
		$$('#pets_1, #pets_2').addEvent('click', function(){
			_click(this);
		});

		if ($('pets_1').getProperty('checked'))
		{
			_click($('pets_1'));
			
		}
		else
		{
			if ($('pets_2').getProperty('checked'))
				_click($('pets_2'));
		}
	});

	function _click(obj)
	{
		if (obj.checked)
		{
			$$('input[id*=pets]').set('disabled', true).set('checked', false);
			obj.set('disabled', false).set('checked', true);
		}
		else
		{
			$$('input[id*=pets]').set('disabled', false).set('checked', false);
		}
	}
//-->
</script>