<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');


?>
<div id="main">
  <div class="headMessage"> <span class="contactUs">
    <h5>Questions?</h5>
    <a href="/about/faq/" class=" ">Help/FAQs</a> <span class="veryCalm">|</span> <a href="index.php?option=com_rental&view=about&layout=feedback-form&format=raw" class="feedbackBox cboxElement">Email us</a> <span class="veryCalm">|</span> <strong>646-504-2787</strong> </span>
    <h1>Create your Profile</h1>
    <h2>Just a few questions so we know who you are.</h2>
    <div class="clear"></div>
  </div>
  
  <!--right column-->
  <div id="rightCol">
    <div class="shadowOuterWhite">
      <div class="shadowInnerWhite">
        <div class="testimonial curve first marginBottom20"> "As a Licensed Real Estate Agent with Citi Habitats, Naked Apartments has been a fantastic element for my professional business"
          <p class="attribution">George <span class="calm">Licensed Salesperson</span> </p>
        </div>
        <div class="testimonial curve  marginBottom20"> "naked apartments has been a huge help with generating leads ...my #1 lead generator"
          <p class="attribution">Bobby <span class="calm">Licensed Salesperson</span> </p>
        </div>
        <div class="testimonial curve marginBottom20"> "I use your site religiously...it has increased business for me!"
          <p class="attribution">Ikenna <span class="calm">Licensed Salesperson</span></p>
        </div>
        <div class="testimonial curve marginBottom20"> "...a slew of happy renters and brokers, excited to put Craigslist behind them.   "
          <p class="attribution">The New York Observer <span class="calm">Respected Publication</span></p>
        </div>
        <div class="clear"></div>
        <span class="sideMod">
        <h2>You are who you state you are</h2>
        <p class="calm">By signing up you are stating that you are either a broker or a landlord, have the authority to represent the listings you upload and are using the site for tenant screening purposes. </p>
        </span>
        <table cellspacing="0" cellpadding="2" border="0" title="Click to Verify - This site chose VeriSign? SSL for secure e-commerce and confidential communications." id="verisign">
          <tbody>
            <tr>
              <td valign="top" align="right"><script src="https://seal.verisign.com/getseal?host_name=www.nakedapartments.com&amp;size=M&amp;use_flash=NO&amp;use_transparent=NO&amp;lang=en"></script></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  
  <!--left column-->
  <div id="leftCol">
    <form method="post" id="new_broker" enctype="multipart/form-data" class="new_broker" action="/broker/signup?plan_id=11" accept-charset="UTF-8">
      <div style="margin:0;padding:0;display:inline">
        <input type="hidden" value="✓" name="utf8">
        <input type="hidden" value="kL5H/rwTqUr+/YrpZvnp3XjwGkEEW5vB2TUGUgwFebw=" name="authenticity_token">
      </div>
      <fieldset class="main noBorder">
        <h2 class=" ">Your Personal Information</h2>
        <div class="rowLine" id="name">
          <label for="user_first_name">First Name</label>
          <input type="text" size="23" name="user[first_name]" id="user_first_name" class="text idleField">
          <div class="clear"></div>
        </div>
        <div class="rowLine">
          <label for="user_last_name">Last Name</label>
          <input type="text" size="23" name="user[last_name]" id="user_last_name" class="text idleField">
          <div class="clear"></div>
        </div>
        <div class="rowLine" id="email">
          <label for="user_email">Email</label>
          <span class="help"> If you have a <strong>RealtyMX</strong> or <strong>OLR</strong> account and 
          want us to auto-import your listings daily, use the <strong>same email address</strong> for both 
          that and your Naked account. </span>
          <input type="text" size="23" name="user[email]" id="user_email" class="text idleField">
          <div class="clear"></div>
        </div>
        <div class="rowLine" id="phone">
          <label for="user_phone_number">Phone Number</label>
          <span class="help">Use a <strong>valid, working phone number</strong> so renters can contact you directly.</span>
          <input type="text" size="2" name="user[phone_area]" maxlength="3" id="user_phone_area" class="text idleField">
          <input type="text" size="2" name="user[phone_prefix]" maxlength="3" id="user_phone_prefix" class="text idleField">
          <input type="text" size="3" name="user[phone_sufix]" maxlength="4" id="user_phone_sufix" class="text idleField">
          <div class="clear"></div>
        </div>
      </fieldset>
      <fieldset class="main">
        <h2 class=" ">Your Password <span class="message inline">(Min. 4 characters)</span> </h2>
        <div class="rowLine">
          <label for="user_password">Password</label>
          <input type="password" size="20" name="user[password]" id="user_password" class="text idleField">
          <div class="clear"></div>
        </div>
      </fieldset>
      <fieldset class="main">
        <h2 class=" ">Your Professional Information</h2>
        <div id="brokerEntityChoices" class="rowSingle">
          <label class="radio">
            <input type="radio" value="1" name="broker[entity_type]" id="broker_entity_type_1" checked="checked">
            Broker/salesperson</label>
          <label class="radio">
            <input type="radio" value="2" name="broker[entity_type]" id="broker_entity_type_2">
            Landlord</label>
          <label class="radio">
            <input type="radio" value="3" name="broker[entity_type]" id="broker_entity_type_3">
            Management company</label>
          <div class="clear"></div>
        </div>
        <div class="hidden" id="brokerProfileDetails" style="display: block;">
          <div class="rowLine">
            <label>Brokerage Firm <span class="message">(optional)</span></label>
            <select name="broker[brokerage_firm_id]" id="brokerageFirm">
              <option value=""></option>
              <option value="23">A.C. Lawrence &amp; Company</option>
              <option value="79">Alpha Properties NYC</option>
              <option value="18">Anchor Associates</option>
              <option value="120">AptsandLofts.com</option>
              <option value="39">Ardor NY</option>
              <option value="125">Barak Realty</option>
              <option value="12">Best Apartments</option>
              <option value="21">Blackstone Properties</option>
              <option value="5">Bond New York</option>
              <option value="17">Caliber Associates</option>
              <option value="2">Citi-Habitats</option>
              <option value="94">City Connections</option>
              <option value="25">City Sites</option>
              <option value="1">Corcoran</option>
              <option value="3">Douglas Elliman</option>
              <option value="118">DSA Realty</option>
              <option value="58">Exit Realty Landmark</option>
              <option value="48">Gotham Realty Services</option>
              <option value="4">Halstead</option>
              <option value="29">Hecht Group</option>
              <option value="83">Hudson Properties</option>
              <option value="115">Ideal Properties Group</option>
              <option value="90">Key New York</option>
              <option value="114">KIAN Realty NYC</option>
              <option value="20">KVNY</option>
              <option value="64">Level Group</option>
              <option value="121">Linnaeus Group</option>
              <option value="96">Manhattan Apartments</option>
              <option value="65">Manhattan Connection</option>
              <option value="6">Mark David</option>
              <option value="111">Metropolis</option>
              <option value="46">Miron Properties</option>
              <option value="103">MNS</option>
              <option value="93">Platinum Properties</option>
              <option value="14">Plaza RE Group</option>
              <option value="91">Rapid Realty</option>
              <option value="35">RE/ACTION International Inc.</option>
              <option value="95">Rutenberg Realty</option>
              <option value="13">Skyline Group</option>
              <option value="113">Spire Group Real Estate</option>
              <option value="7">The Real Estate Group</option>
              <option value="133">Urban Apartments of New York</option>
              <option value="92">Wiechert, Realtors</option>
              <option value="999">Other</option>
            </select>
            <input type="text" value="" style="display:none" size="20" name="broker[brokerage_firm_other]" id="broker_brokerage_firm_other" default="Enter brokerage name" class="text idleField">
            <div class="clear"></div>
          </div>
          <div class="rowLine" id="lic"> <span class="help">We need this to verify your status. See our <a data-height="600" data-width="600" class="ajaxModal cboxElement" href="/ajax/privacy_policy">Privacy Policy</a> for details.</span>
            <label>License Number<br>
              <span class="message"> of Broker/Salesperson</span> </label>
            <input type="text" size="20" name="broker[license_number]" id="broker_license_number" class="text idleField">
            <div class="clear"></div>
          </div>
        </div>
        <div id="myWebSite" class="rowLine">
          <label for="broker_my_web_site"><a title="" class="tooltip mouseover" href="#">My web site</a> <span class="message">(optional)</span></label>
          <input type="text" size="50" name="broker[my_web_site]" id="broker_my_web_site" class="text idleField">
          <div class="clear"></div>
        </div>
        <div class="hidden" id="landlordProfileDetails" style="display: none;">
          <div class="rowLine">
            <label for="broker_landlord_meta_attributes_company_name">Name of company</label>
            <input type="text" size="20" name="broker[landlord_meta_attributes][company_name]" id="broker_landlord_meta_attributes_company_name" class="text idleField">
            <div class="clear"></div>
          </div>
          <div class="rowLine">
            <label for="broker_landlord_meta_attributes_apartments_managed">Number of apartments you manage</label>
            <input type="text" size="5" name="broker[landlord_meta_attributes][apartments_managed]" id="broker_landlord_meta_attributes_apartments_managed" class="text idleField">
            <div class="clear"></div>
          </div>
          <h2>Info on one apartment you will advertise</h2>
          <div class="rowLine hidden" style="display: none;">
            <label for="broker_landlord_meta_attributes_landlord_name">Landlord name</label>
            <input type="text" size="20" name="broker[landlord_meta_attributes][landlord_name]" id="broker_landlord_meta_attributes_landlord_name" class="text idleField">
            <div class="clear"></div>
          </div>
          <div class="rowLine"> <span class="help">We need the address for verification purposes. It will not be displayed to renters.</span>
            <label for="broker_landlord_meta_attributes_apartment_street_address">Street address</label>
            <input type="text" size="20" name="broker[landlord_meta_attributes][apartment_street_address]" id="broker_landlord_meta_attributes_apartment_street_address" class="text idleField">
            <div class="clear"></div>
          </div>
          <div class="rowLine">
            <label for="broker_landlord_meta_attributes_apartment_unit_number">Unit number</label>
            <input type="text" size="5" name="broker[landlord_meta_attributes][apartment_unit_number]" id="broker_landlord_meta_attributes_apartment_unit_number" class="text idleField">
            <div class="clear"></div>
          </div>
          <div class="rowLine">
            <label for="broker_landlord_meta_attributes_apartment_borough_id">Borough</label>
            <select name="broker[landlord_meta_attributes][apartment_borough_id]" id="broker_landlord_meta_attributes_apartment_borough_id">
              <option value="">Please select</option>
              <option value="4">Bronx</option>
              <option value="2">Brooklyn</option>
              <option value="1">Manhattan</option>
              <option value="3">Queens</option>
              <option value="5">Staten Island</option>
            </select>
            <div class="clear"></div>
          </div>
          <div class="rowLine">
            <label for="broker_landlord_meta_attributes_property_registration_number">Property registration number</label>
            <input type="text" size="20" name="broker[landlord_meta_attributes][property_registration_number]" id="broker_landlord_meta_attributes_property_registration_number" class="text idleField">
            <div class="clear"></div>
          </div>
        </div>
      </fieldset>
      <fieldset id="planDetails" class="main">
        <h2>Plan Details</h2>
        <div class="rowLine"> <span class="text120"><strong>Plus</strong>: $39/mo</span> </div>
        <div class="clear"></div>
        <div id="planFreq">
          <h4 class="rowLine">Automatically charge my card:</h4>
          <div class="checkboxCont">
            <input type="radio" value="1" name="months_per_billing_cycle" id="months_per_billing_cycle_1" data-renewal-date="06/12/2012" checked="checked">
            <label for="months_1">Every Month </label>
          </div>
          <div class="checkboxCont">
            <input type="radio" value="3" name="months_per_billing_cycle" id="months_per_billing_cycle_3" data-renewal-date="08/12/2012">
            <label for="months_3">Every 3 Months <span class="savings">$111.15 <span class="percent">(save 5%)</span></span></label>
          </div>
          <div class="checkboxCont">
            <input type="radio" value="6" name="months_per_billing_cycle" id="months_per_billing_cycle_6" data-renewal-date="11/12/2012">
            <label for="months_6">Every 6 Months <span class="savings">$210.60 <span class="percent">(save 10%)</span></span></label>
          </div>
          <div class="checkboxCont">
            <input type="radio" value="12" name="months_per_billing_cycle" id="months_per_billing_cycle_12" data-renewal-date="05/12/2013">
            <label for="months_12">Every Year <span class="savings">$351.00 <span class="percent">(save 25%)</span></span></label>
          </div>
          <div class="clear"></div>
          <p class="note"> <span class="highlightYellow">Your card will be charged automatically each payment period.</span><br>
            For example, if you choose "Every Month" your card will be charged each month. </p>
          <p class="note"> <span class="highlightYellow">You can cancel anytime during your membership.</span><br>
            Just click "View Account" and then click "Cancel Account". If you don't cancel, your plan will continue. </p>
          <p class="note"> <span class="highlightYellow">Your card will be charged again on <span id="subscriptionNextRenewalAt">06/12/2012</span>. </span> </p>
          <div class="clear"></div>
        </div>
        <input type="hidden" value="11" name="plan_id" id="plan_id">
        <input type="hidden" value="signup" name="plan_state" id="plan_state">
      </fieldset>
      <fieldset class="main" id="cardInfo">
        <h2>Payment Information <span class="message inline"> We accept Credit, Debit and Prepaid Cards.</span></h2>
        <div class="rowLine">
          <label>Card Type</label>
          <select tabindex="1" name="billing_information[credit_card_type]" id="billing_information_credit_card_type">
            <option value="master">Mastercard</option>
            <option value="discover">Discover</option>
            <option value="visa">Visa</option>
            <option value="american_express">American Express</option>
          </select>
          <div class="clear"></div>
        </div>
        <div class="rowLine">
          <label>Card Number</label>
          <input type="text" tabindex="2" size="20" name="billing_information[credit_card_number]" id="billing_information_credit_card_number" class="idleField">
          <div class="clear"></div>
        </div>
        <div class="rowLine"> <span class=" help">Please enter your name exactly as it appears on your card</span>
          <label>Cardholder's First Name</label>
          <input type="text" tabindex="3" size="20" name="billing_information[credit_card_first_name]" id="billing_information_credit_card_first_name" class="idleField">
          <div class="clear"></div>
        </div>
        <div class="rowLine">
          <label>Cardholder's Last Name</label>
          <input type="text" tabindex="4" size="20" name="billing_information[credit_card_last_name]" id="billing_information_credit_card_last_name" class="idleField">
          <div class="clear"></div>
        </div>
        <div class="rowLine">
          <label>Expiration Date</label>
          <select tabindex="5" name="billing_information[credit_card_month]" id="billing_information_credit_card_month">
            <option value="1">01 - Jan</option>
            <option value="2">02 - Feb</option>
            <option value="3">03 - Mar</option>
            <option value="4">04 - Apr</option>
            <option value="5">05 - May</option>
            <option value="6">06 - Jun</option>
            <option value="7">07 - Jul</option>
            <option value="8">08 - Aug</option>
            <option value="9">09 - Sep</option>
            <option value="10">10 - Oct</option>
            <option value="11">11 - Nov</option>
            <option value="12">12 - Dec</option>
          </select>
          <select tabindex="6" name="billing_information[credit_card_year]" id="billing_information_credit_card_year" class="second">
            <option value="2012">2012</option>
            <option value="2013">2013</option>
            <option value="2014">2014</option>
            <option value="2015">2015</option>
            <option value="2016">2016</option>
            <option value="2017">2017</option>
            <option value="2018">2018</option>
            <option value="2019">2019</option>
            <option value="2020">2020</option>
            <option value="2021">2021</option>
            <option value="2022">2022</option>
            <option value="2023">2023</option>
            <option value="2024">2024</option>
            <option value="2025">2025</option>
            <option value="2026">2026</option>
            <option value="2027">2027</option>
            <option value="2028">2028</option>
            <option value="2029">2029</option>
            <option value="2030">2030</option>
            <option value="2031">2031</option>
            <option value="2032">2032</option>
            <option value="2033">2033</option>
            <option value="2034">2034</option>
            <option value="2035">2035</option>
            <option value="2036">2036</option>
            <option value="2037">2037</option>
            <option value="2038">2038</option>
            <option value="2039">2039</option>
            <option value="2040">2040</option>
            <option value="2041">2041</option>
            <option value="2042">2042</option>
          </select>
          <div class="clear"></div>
        </div>
        <div class="rowLine">
          <label for="cardCVC">CVC <span title="On MasterCard and Visa, this is the last 3 digits AFTER the credit card number in the signature area of the card. On American Express cards, it's the 4-digit  number above the credit card number on either the right or the left side of the card." class="calm tooltip mouseover">what's this?</span></label>
          <input type="text" tabindex="7" size="3" name="billing_information[credit_card_verification_value]" id="billing_information_credit_card_verification_value" class="idleField">
          <div class="clear"></div>
        </div>
        <h4 class="rowLine"> Billing Address </h4>
        <div class="rowLine">
          <label for="billAddress">Street Address</label>
          <input type="text" tabindex="8" size="20" name="billing_information[billing_address_address]" id="billing_information_billing_address_address" class="idleField">
          <div class="clear"></div>
        </div>
        <div class="rowLine">
          <label for="billZip">Zip</label>
          <input type="text" tabindex="11" size="5" name="billing_information[billing_address_zip]" id="billing_information_billing_address_zip" class="idleField">
          <div class="clear"></div>
        </div>
      </fieldset>
      <fieldset class="main">
        <h2>Coupons/Discounts</h2>
        <div id="newCoupon"> Enter any coupons or discounts
          <div class="clear"></div>
          <span class="block">
          <input type="text" id="couponCode" name="code" size="30" class="text idleField">
          </span> <a id="applyCouponCode" class="button white noIcon medium" href="#"><span>Apply Discount</span></a>
          <div class="clear"></div>
        </div>
      </fieldset>
      <fieldset class="main">
        <h2><a class="more" onclick="$('#specialities').is(':hidden') ? $('#specialities').fadeIn('fast') : $('#specialities').fadeOut('fast'); return false;" href=""> Select Neighborhood Specialities</a> <span class="message inline">(optional)</span></h2>
        <div style="display:none" id="specialities">
          <ul class="clearfix" id="boroughNav">
            <li data-id="1" class="active"><a href="#">Manhattan</a></li>
            <li data-id="2"><a href="#">Brooklyn</a></li>
            <li data-id="3"><a href="#">Queens</a></li>
            <li data-id="4"><a href="#">Bronx</a></li>
            <li data-id="5"><a href="#">Staten Island</a></li>
          </ul>
          <div style="" class="boroughs" id="borough_1">
            <div class="clearfix" id="filters">
              <div class="checkboxCont"> <a data-id="1" href="#" class="selectAll button white noIcon medium"><span>Select All</span></a> </div>
              <div class="checkboxCont"> <a data-id="1" href="#" class="unselectAll button white noIcon medium"><span>Unselect All</span></a> </div>
            </div>
            <span>
            <div class="checkboxCont">
              <input type="checkbox" value="23" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Battery Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="6" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Chelsea</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="21" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Chinatown</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="191" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Clinton</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="18" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>East Village</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="24" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Financial District</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="76" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Flatiron</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="10" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Gramercy</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="14" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Greenwich Village</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="1" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Harlem</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="5" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Hell's Kitchen</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="25" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Inwood</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="93" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Kips Bay</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="22" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Little Italy</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="17" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Lower East Side</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="13" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Meatpacking Dist.</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="72" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Midtown</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="155" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Midtown Center</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="16" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Midtown East</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="15" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Midtown West</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="2" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Morningside Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="9" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Murray Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="20" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>NoHo</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="19" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Nolita</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="73" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Roosevelt Island</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="7" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>SoHo</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="192" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Theater District/Times Square</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="8" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>TriBeCa</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="74" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Tudor City</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="11" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Union Square</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="4" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Upper East Side</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="3" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Upper West Side</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="26" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Washington Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="12" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>West Village</label>
            </div>
            </span>
            <div class="clear"></div>
          </div>
          <div style="display: none;" class="boroughs" id="borough_2">
            <div class="clearfix" id="filters">
              <div class="checkboxCont"> <a data-id="2" href="#" class="selectAll button white noIcon medium"><span>Select All</span></a> </div>
              <div class="checkboxCont"> <a data-id="2" href="#" class="unselectAll button white noIcon medium"><span>Unselect All</span></a> </div>
            </div>
            <span>
            <div class="checkboxCont">
              <input type="checkbox" value="117" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bath Beach</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="77" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bayridge</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="46" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bedford-Stuyvesant</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="29" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bensonhurst</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="78" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bergen Beach</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="36" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Boerum Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="79" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Borough Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="118" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Brighton Beach</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="30" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Brooklyn Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="119" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Brownsville</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="41" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bushwick</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="120" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Canarsie</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="37" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Carroll Gardens</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="31" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Clinton Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="38" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Cobble Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="121" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Coney Island</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="45" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Crown Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="122" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Cypress Hills</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="80" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Ditmas Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="32" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Downtown</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="33" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>DUMBO</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="123" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Dyker Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="124" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>East Flatbush</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="82" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>East New York</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="42" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>East Williamsburg</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="83" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Flatbush</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="84" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Flatlands</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="34" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Fort Greene</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="147" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Fort Hamilton</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="125" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Georgetown</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="39" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Gowanus</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="126" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Gravesend</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="43" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Greenpoint</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="127" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Greenwood Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="151" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Homecrest</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="85" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Kensington</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="128" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Lefferts Garden</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="152" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Manhattan Terrace</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="129" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Marine Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="95" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Midwood</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="130" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Mill Basin</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="86" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Ocean Parkway</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="131" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Old Mill Basin</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="27" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Park Slope</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="94" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Park Slope South</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="28" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Prospect Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="87" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Prospect Leffert</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="134" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Prospect Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="88" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Prospect Park South</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="40" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Red Hook</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="132" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Sheepshead Bay</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="133" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Stuyvesant Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="89" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Sunset Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="35" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Vinegar Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="44" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Williamsburg</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="47" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Windsor Terrace</label>
            </div>
            </span>
            <div class="clear"></div>
          </div>
          <div style="display: none;" class="boroughs" id="borough_3">
            <div class="clearfix" id="filters">
              <div class="checkboxCont"> <a data-id="3" href="#" class="selectAll button white noIcon medium"><span>Select All</span></a> </div>
              <div class="checkboxCont"> <a data-id="3" href="#" class="unselectAll button white noIcon medium"><span>Unselect All</span></a> </div>
            </div>
            <span>
            <div class="checkboxCont">
              <input type="checkbox" value="48" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Astoria</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="99" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bayside</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="102" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Briarwood</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="137" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Browne Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="107" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Cambria Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="148" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Clearview</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="98" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>College point</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="96" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Corona</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="49" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Ditmars</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="149" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Douglaston</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="101" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>East Elmhurst</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="139" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>East Flushing</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="100" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Elmhurst</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="112" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Far Rockaway</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="108" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Floral Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="54" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Flushing</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="55" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Forest Hills</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="190" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Fresh Meadows</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="141" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Glendale</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="92" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Hunters Point</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="53" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Jackson Heights</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="105" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Jamaica</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="97" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Kew Gardens</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="136" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Kew Gardens Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="50" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Long Island City</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="113" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Maspeth</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="114" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Middle Village</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="159" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Murray Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="143" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Neponsit &amp; Belle</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="110" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Ozone Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="144" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Pomonok</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="106" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Queens Village</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="157" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Queensboro Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="91" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Rego Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="104" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Richmond hills</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="115" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Ridgewood</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="146" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Rockaway Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="109" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Rosedale</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="111" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>South Ozone Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="116" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Springfield Gardens</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="51" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Sunnyside</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="103" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Woodhaven</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="52" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Woodside</label>
            </div>
            </span>
            <div class="clear"></div>
          </div>
          <div style="display: none;" class="boroughs" id="borough_4">
            <div class="clearfix" id="filters">
              <div class="checkboxCont"> <a data-id="4" href="#" class="selectAll button white noIcon medium"><span>Select All</span></a> </div>
              <div class="checkboxCont"> <a data-id="4" href="#" class="unselectAll button white noIcon medium"><span>Unselect All</span></a> </div>
            </div>
            <span>
            <div class="checkboxCont">
              <input type="checkbox" value="59" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bedford Park</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="75" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Bronx</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="189" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Castle Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="60" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Concourse</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="61" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>East Tremont</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="150" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Fairmont   Claremont Village</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="57" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Fordham</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="62" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Marble Hill</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="63" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Morrisania</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="187" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Moshulu Parkway</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="58" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Mott Haven</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="64" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Parkchester</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="65" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Pelham Bay</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="66" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Pelham Parkway</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="56" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Riverdale</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="186" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Wakefield</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="188" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Woodlawn</label>
            </div>
            </span>
            <div class="clear"></div>
          </div>
          <div style="display: none;" class="boroughs" id="borough_5">
            <div class="clearfix" id="filters">
              <div class="checkboxCont"> <a data-id="5" href="#" class="selectAll button white noIcon medium"><span>Select All</span></a> </div>
              <div class="checkboxCont"> <a data-id="5" href="#" class="unselectAll button white noIcon medium"><span>Unselect All</span></a> </div>
            </div>
            <span>
            <div class="checkboxCont">
              <input type="checkbox" value="67" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>East Shore</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="68" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Mid-Island</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="69" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>North Shore</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="145" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>Shore Acres</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="70" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>South Shore</label>
            </div>
            <div class="checkboxCont">
              <input type="checkbox" value="71" name="broker[neighborhood_ids][]" id="broker_neighborhood_ids_" class="field text">
              <label>West Shore</label>
            </div>
            </span>
            <div class="clear"></div>
          </div>
        </div>
      </fieldset>
      <fieldset class="main" id="brokerBioPhoto">
        <h2><a class="more" onclick="$('#personalize').is(':hidden') ? $('#personalize').fadeIn('fast') : $('#personalize').fadeOut('fast'); return false;" href="">Personalize Your Profile</a> <span class="message inline">(optional)</span></h2>
        <div style="display:none" id="personalize"> <span class="note">Please don't include your full name or contact information - your account will be suspended</span>
          <div class="rowSingle"> <strong>Write a personal statement/bio (visible to renters)</strong>
            <textarea style="width: 500px; visibility: hidden; display: none;" rows="7" name="broker[bio]" id="broker_bio" cols="60" class="idleField"></textarea>
            <span lang="en" aria-labelledby="cke_broker_bio_arialbl" role="application" title=" " dir="ltr" class="cke_skin_kama cke_1 cke_editor_broker_bio" id="cke_broker_bio"><span class="cke_voice_label" id="cke_broker_bio_arialbl">Rich Text Editor</span><span role="presentation" class="cke_browser_gecko"><span role="presentation" class="cke_wrapper cke_ltr">
            <table cellspacing="0" cellpadding="0" border="0" role="presentation" class="cke_editor">
              <tbody>
                <tr role="presentation" style="-moz-user-select: none;">
                  <td role="presentation" class="cke_top" id="cke_top_broker_bio"><div onmousedown="return false;" aria-labelledby="cke_5" role="group" class="cke_toolbox"><span class="cke_voice_label" id="cke_5">Editor toolbars</span><span role="toolbar" class="cke_toolbar" id="cke_6"><span class="cke_toolbar_start"></span><span role="presentation" class="cke_toolgroup"><span class="cke_button"><a onclick="CKEDITOR.tools.callFunction(4, this); return false;" onfocus="return CKEDITOR.tools.callFunction(3, event);" onkeydown="return CKEDITOR.tools.callFunction(2, event);" onblur="this.style.cssText = this.style.cssText;" aria-labelledby="cke_7_label" role="button" hidefocus="true" tabindex="-1" title="Bold" class="cke_off cke_button_bold" id="cke_7"><span class="cke_icon">&nbsp;</span><span class="cke_label" id="cke_7_label">Bold</span></a></span><span class="cke_button"><a onclick="CKEDITOR.tools.callFunction(7, this); return false;" onfocus="return CKEDITOR.tools.callFunction(6, event);" onkeydown="return CKEDITOR.tools.callFunction(5, event);" onblur="this.style.cssText = this.style.cssText;" aria-labelledby="cke_8_label" role="button" hidefocus="true" tabindex="-1" title="Italic" class="cke_off cke_button_italic" id="cke_8"><span class="cke_icon">&nbsp;</span><span class="cke_label" id="cke_8_label">Italic</span></a></span><span class="cke_button"><a onclick="CKEDITOR.tools.callFunction(10, this); return false;" onfocus="return CKEDITOR.tools.callFunction(9, event);" onkeydown="return CKEDITOR.tools.callFunction(8, event);" onblur="this.style.cssText = this.style.cssText;" aria-labelledby="cke_9_label" role="button" hidefocus="true" tabindex="-1" title="Underline" class="cke_off cke_button_underline" id="cke_9"><span class="cke_icon">&nbsp;</span><span class="cke_label" id="cke_9_label">Underline</span></a></span><span role="separator" class="cke_separator"></span><span class="cke_button"><a onclick="CKEDITOR.tools.callFunction(13, this); return false;" onfocus="return CKEDITOR.tools.callFunction(12, event);" onkeydown="return CKEDITOR.tools.callFunction(11, event);" onblur="this.style.cssText = this.style.cssText;" aria-labelledby="cke_10_label" role="button" hidefocus="true" tabindex="-1" title="Insert/Remove Numbered List" class="cke_off cke_button_numberedlist" id="cke_10"><span class="cke_icon">&nbsp;</span><span class="cke_label" id="cke_10_label">Insert/Remove Numbered List</span></a></span><span class="cke_button"><a onclick="CKEDITOR.tools.callFunction(16, this); return false;" onfocus="return CKEDITOR.tools.callFunction(15, event);" onkeydown="return CKEDITOR.tools.callFunction(14, event);" onblur="this.style.cssText = this.style.cssText;" aria-labelledby="cke_11_label" role="button" hidefocus="true" tabindex="-1" title="Insert/Remove Bulleted List" class="cke_off cke_button_bulletedlist" id="cke_11"><span class="cke_icon">&nbsp;</span><span class="cke_label" id="cke_11_label">Insert/Remove Bulleted List</span></a></span><span role="separator" class="cke_separator"></span><span class="cke_button"><a onclick="CKEDITOR.tools.callFunction(19, this); return false;" onfocus="return CKEDITOR.tools.callFunction(18, event);" onkeydown="return CKEDITOR.tools.callFunction(17, event);" onblur="this.style.cssText = this.style.cssText;" aria-labelledby="cke_12_label" role="button" hidefocus="true" tabindex="-1" title="Undo" class="cke_button_undo cke_disabled" id="cke_12" aria-disabled="true"><span class="cke_icon">&nbsp;</span><span class="cke_label" id="cke_12_label">Undo</span></a></span><span class="cke_button"><a onclick="CKEDITOR.tools.callFunction(22, this); return false;" onfocus="return CKEDITOR.tools.callFunction(21, event);" onkeydown="return CKEDITOR.tools.callFunction(20, event);" onblur="this.style.cssText = this.style.cssText;" aria-labelledby="cke_13_label" role="button" hidefocus="true" tabindex="-1" title="Redo" class="cke_button_redo cke_disabled" id="cke_13" aria-disabled="true"><span class="cke_icon">&nbsp;</span><span class="cke_label" id="cke_13_label">Redo</span></a></span></span><span class="cke_toolbar_end"></span></span></div>
                    <a onclick="CKEDITOR.tools.callFunction(23)" class="cke_toolbox_collapser" tabindex="-1" id="cke_14" title="Collapse Toolbar"><span>▲</span></a></td>
                </tr>
                <tr role="presentation">
                  <td role="presentation" style="height:200px" class="cke_contents" id="cke_contents_broker_bio"><iframe frameborder="0" allowtransparency="true" tabindex="0" src="" title="Rich text editor, broker_bio, press ALT 0 for help." style="width:100%;height:100%"></iframe></td>
                </tr>
                <tr role="presentation" style="-moz-user-select: none;">
                  <td role="presentation" class="cke_bottom" id="cke_bottom_broker_bio"><div onmousedown="CKEDITOR.tools.callFunction(1, event)" title="Drag to resize" class="cke_resizer cke_resizer_ltr"></div></td>
                </tr>
              </tbody>
            </table>
            <style>
.cke_skin_kama{visibility:hidden;}
</style>
            </span></span><span role="presentation" style="position:absolute;" tabindex="-1"></span></span> </div>
          <span class="rowLeft">
          <label><strong>Upload a photo</strong></label>
          <input type="file" name="broker[photo]" id="broker_photo" class="idleField">
          </span> </div>
      </fieldset>
      <div class="formActions green">
        <div class="disclaimer"> By clicking this button, you are indicating that you have read and agree to the <a data-height="600" data-width="600" class="ajaxModal cboxElement" href="/ajax/broker_terms_of_service">Terms of Service</a></div>
        <a title="Create my account" class="button green large" id="submitBrokerSignup" href=""><span>Create Profile</span></a> <a class="cancel" href="/">Cancel</a>
        <div class="clear"></div>
      </div>
    </form>
  </div>
  
  <!--end container-->
  <div class="clear"></div>
</div>