<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

//get item
$items = $this->items;
?>


<div class="<?php echo $this->boroughInfo->alias; ?>">
	<?php if ( !empty($items->sub_category) ): ?>
	<div class="floatLeft" id="parentNeighborhoods">
		<div class="floatLeft">
			<ol>
				<?php foreach ($items->sub_category as $cat): ?>
				<li data-type="parent"><input type="checkbox" value="<?php echo $cat->id; ?>"
					data-type="parent" /> <?php echo $cat->title; ?></li>
				<?php endforeach; ?>
			</ol>
		</div>
	</div>
	<?php endif; ?>
	
	<div class="floatLeft" id="neighborhoods">
	
		<div class="neighborhoodOptionColumn">
			<ul>
				<?php foreach ($items->locations as $loc): ?>
				<li><input type="checkbox" value="<?php echo $loc->id; ?>" data-type="child"
					data-parent-ids="~<?php echo $loc->catid; ?>" /> <?php echo $loc->title; ?></li>
				<?php endforeach; ?>
			</ul>
		</div>

	</div>
	<div class="clear"></div>
</div>

