<?php
/**
 * version $Id: view.html.php $
 * @package		Joomla.Site
 * @subpackage	com_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die;

jimport('joomla.application.component.view');

/**
 * HTML View class for the Content component
 *
 * @package		Joomla.Site
 * @subpackage	com_content
 * @since 1.5
 */

class RentalViewBroker extends JView
{
	protected $items;
	protected $pagination;
	protected $checkErrors;
	protected $checkEmailAddress = '';
	protected $neighborhood;

	function display($tpl = null)
	{
		// Check for errors.
		if (count($errors = $this->get('Errors'))) {
			JError::raiseError(500, implode("\n", $errors));
			return false;
		}
		
		$session = JFactory::getSession();
		
		// reset session errors
		$session->set('errors', null);

		$this->_prepareDocument();
		
		$post = JRequest::get('post');
		
		$user = $post['user'];
		
		$errors = array();
		$this->checkErrors = array();
		
		//check valid
		if ($user['first_name'] == '')
			$errors[] = 'First name can\'t be blank';
		
		if ($user['last_name'] == '')
			$errors[] = 'Last name can\'t be blank';
		
		if ($user['email'] == '')
			$errors[] = 'Email can\'t be blank';
		elseif (!$this->checkValidEmail($user['email']))
		{
			$session->set('error_email', 'INVALID');
			$errors[] = 'Email should look like an email address';
		}
		
		$model = JModel::getInstance('Renter', 'RentalModel');
		
		$checkEmailExist = $model->checkEmailExist($user['email']);
		
		if ($checkEmailExist)
		{
			$session->set('error_email', 'TAKEN');
			$errors[] = 'Email has already been taken';
		}
		
		if (strlen($user['phone_area']) == '')
			$errors[] = 'Phone area can\'t be blank';
		
		if (strlen($user['phone_prefix']) == '')
			$errors[] = 'Phone prefix can\'t be blank';
		
		if (strlen($user['phone_sufix']) == '')
			$errors[] = 'Phone sufix can\'t be blank';
		
		if (strlen($user['password']) < 4)
		{
			$errors[] = 'Password is too short (minimum is 4 characters)';
		}
		
		$broker = $post['broker'];
		
		//get neighborhood
		$this->neighborhood = $model->getNeighborhood();
		
		/*
		if ($broker['license_number'] == '')
			$errors[] = 'License number can\'t be blank';
		 */
		
		// check credit card info
		$billing_information = $post['billing_information'];
		
		if ($billing_information['credit_card_number'] == '')
			$errors[] = 'Credit card number can\'t be blank';
		
		if ($billing_information['credit_card_first_name'] == '')
			$errors[] = 'Credit card first name can\'t be blank';
		
		if ($billing_information['credit_card_last_name'] == '')
			$errors[] = 'Credit card last name can\'t be blank';
		
		if ($billing_information['credit_card_verification_value'] == '')
			$errors[] = 'Credit card CVC can\'t be blank';
		
		if ($billing_information['billing_address_address'] == '')
			$errors[] = 'Street Address can\'t be blank';
		
		if ($billing_information['billing_address_zip'] == '')
			$errors[] = 'Zip can\'t be blank';
		
		
		if (!empty($errors))
		{
			$session->set('post', $post);
			$session->set('errors', $errors);
			self::url_redirect();
		}
		else
		{
			$brokerModel = $this->getModel();
			
			//reg user
			$result = $brokerModel->register($user, $post);
				
			//if reg done
			if ($result === true)
			{
				//unset session errors & post
				$session->set('errors', null);
				$session->set('post', null);
				
				//set session new user			
				$session->set('SESSION_NEW_USER', 1);
			
				//TODO: login with email & password user provided when reg
				
				//TODO: redirect to list page
				header('Location: ' . JRoute::_('index.php?option=com_rental&view=apartments'));
				jexit();			
			}
		}
		
		jexit();

		//parent::display($tpl);
	}
	
	/**
	 * Prepares the document
	 */
	protected function _prepareDocument()
	{
		//TODO: prepare document
	}
	
	function checkValidEmail($email = '')
	{
		return preg_match("^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$^", $email);
	}
	
	function url_redirect()
	{
		header ("Location: " . JRoute::_('index.php?option=com_rental&view=broker&layout=signup'));
		exit();
	}
}
