<?php
/**
 * @version		$Id: apartment.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.helper');

/**
 * Apartment model for the rental component.
 *
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @since		1.6
 */
class RentalModelApartment extends JModel
{
	/**
	 * Gets a list of apartment
	 *
	 * @return	#x# object or false.
	 * @since	1.6
	 */
	function getItem()
	{
		//init vars
		$db			= $this->getDbo();
		$id 		= JRequest::getInt('id');
		$query		= $db->getQuery(true);
		
		$query->select(
			'a.id , a.bedrooms, a.bathrooms, a.square_ft, a.listed_for, a.available_on, a.description, a.address, a.address_2, a.city, a.portal_code, a.country, a.price, a.images'
		);
		
		$query->from('`#__rental_apartments` a');
		
		// Join over the retal_agents
		$query->select('agent.user_id AS  agent_user_id, agent.first_name AS agent_first_name, agent.last_name AS agent_last_name');
		$query->join('INNER', '#__retal_agents AS agent ON agent.id = a.agent_id');
		
		$query->where('a.id = ' . $id);
		
		$db->setQuery($query);
		$record = $db->loadObject();
		
		if ($record)
		{
			$amenities = $this->_getAmenities($record->id);
			
			$record->amenities = implode(', ', $amenities);
			
			//extract images
			$images = @unserialize($record->images);
			
			$recImages = array();
			$recFloorPlan = array();
			
			if (!empty($images))
			{
				foreach ($images as $img)
				{
					if ($img['type'] == 'images')
						$recImages[] = $img;
					else 
						$recFloorPlan[] = $img;
				}
			}
			
			$record->list_images = $recImages;
			$record->list_floor_plan = $recFloorPlan;
			
			return $record;
		}
			
		return false;
	}
	
	private function _getAmenities($apartmentId)
	{
		$db = JFactory::getDbo();
		$query = $db->getQuery(true);
		
		$query->select('a.title')
			->from('#__retal_apartment_amenities aa')
			->join('INNER', '#__rental_amenities a ON a.id = aa.amenities_id')
			->where('aa.apartment_id = ' . (int) $apartmentId)
			->order('a.title');
		
		$db->setQuery($query);
		$amenities = $db->loadResultArray();
		
		return $amenities;
	}
}