<?php
/**
 * @version		$Id: apartment.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.helper');

/**
 * Apartment model for the rental component.
 *
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @since		1.6
 */
class RentalModelApartment extends JModel
{
	/**
	 * Gets a list of apartment
	 *
	 * @return	#x# object or false.
	 * @since	1.6
	 */
	function getItem()
	{
		//init vars
		$db			= $this->getDbo();
		$id 		= JRequest::getInt('id');
		$query		= $db->getQuery(true);
		
		$query->select(
			'`#__rental_apartments`.id , #__rental_apartments.bedrooms, #__rental_apartments.bathrooms, #__rental_apartments.square_ft, #__rental_apartments.listed_for, #__rental_apartments.available_on, #__rental_apartments.description, #__rental_apartments.address, #__rental_apartments.address_2, #__rental_apartments.city, #__rental_apartments.portal_code, #__rental_apartments.country, #__rental_apartments.price'
		);
		
		$query->from('`#__rental_apartments`');
		
		// Join over the retal_agents
$query->select('retal_agents_0.first_name AS retal_agents_0_first_name, retal_agents_0.last_name AS retal_agents_0_last_name');
$query->join('INNER', '#__retal_agents AS retal_agents_0 ON retal_agents_0.id = #__rental_apartments.agent_id');



		$query->where('`#__rental_apartments`.id = ' . $id);
		
		$db->setQuery($query);
		$record = $db->loadObject();
		
		if($record)
			return $record;
			
		return false;
	}
}