<?php
/**
 * @version		$Id: saved.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');
jimport('joomla.application.component.helper');

/**
 * Saved model for the rental component.
 *
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @since		1.6
 */
class RentalModelSaved extends JModelList
{
	/**
	 * Gets a list of saved
	 *
	 * @return	array	An array of saved objects.
	 * @since	1.6
	 */
	function getListQuery()
	{
		$db			= $this->getDbo();
		$query		= $db->getQuery(true);
		
		$query->select(
			'#__retal_user_saved_search.id , #__retal_user_saved_search.search_phrase, #__retal_user_saved_search.created'
		);
		
		$query->from('`#__retal_user_saved_search`');
		
		// Join over the users
$query->select('users_0.username AS users_0_username');
$query->join('INNER', '#__users AS users_0 ON users_0.id = #__retal_user_saved_search.user_id');



		return $query;
	}
}