<?php
/**
 * @version		$Id: edit.php $
 * @package		Joomla.Administrator
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers/html');
JHtml::_('behavior.tooltip');
JHtml::_('behavior.formvalidation');
?>
<script type="text/javascript">
	Joomla.submitbutton = function(task)
	{
		if (task == 'agent.cancel' || document.formvalidator.isValid(document.id('agent-form'))) {
			Joomla.submitform(task, document.getElementById('agent-form'));
		}
	}
</script>

<form action="<?php echo JRoute::_('index.php?option=com_rental&layout=edit&id='.(int) $this->item->id); ?>" method="post" name="adminForm" id="agent-form" class="form-validate" enctype="multipart/form-data">
	<div class="width-60 fltlft">
		<fieldset class="adminform">
			<legend><?php echo empty($this->item->id) ? JText::_('COM_RENTAL_NEW_AGENT') : JText::sprintf('COM_RENTAL_AGENT_DETAILS', $this->item->id); ?></legend>
			<ul class="adminformlist">
				
				<li><?php echo $this->form->getLabel('user_id'); ?>
				<?php echo $this->form->getInput('user_id'); ?></li>
				
				<li><?php echo $this->form->getLabel('first_name'); ?>
				<?php echo $this->form->getInput('first_name'); ?></li>
				
				<li><?php echo $this->form->getLabel('last_name'); ?>
				<?php echo $this->form->getInput('last_name'); ?></li>
				
				<li><?php echo $this->form->getLabel('phone_area'); ?>
				<?php echo $this->form->getInput('phone_area'); ?></li>
				
				<li><?php echo $this->form->getLabel('phone_prefix'); ?>
				<?php echo $this->form->getInput('phone_prefix'); ?></li>
				
				<li><?php echo $this->form->getLabel('phone_sufix'); ?>
				<?php echo $this->form->getInput('phone_sufix'); ?></li>
				
				<li><?php echo $this->form->getLabel('broker_entity_type'); ?>
				<?php echo $this->form->getInput('broker_entity_type'); ?></li>
				
				<li><?php echo $this->form->getLabel('brokerage_firm_other'); ?>
				<?php echo $this->form->getInput('brokerage_firm_other'); ?></li>				
				
				<li><?php echo $this->form->getLabel('license_number'); ?>
				<?php echo $this->form->getInput('license_number'); ?></li>				
				
				<li><?php echo $this->form->getLabel('my_web_site'); ?>
				<?php echo $this->form->getInput('my_web_site'); ?></li>				
				
				<li><?php echo $this->form->getLabel('months_per_billing_cycle'); ?>
				<?php echo $this->form->getInput('months_per_billing_cycle'); ?></li>				
				
				<li><?php echo $this->form->getLabel('credit_card_type'); ?>
				<?php echo $this->form->getInput('credit_card_type'); ?></li>				
				
				<li><?php echo $this->form->getLabel('credit_card_number'); ?>
				<?php echo $this->form->getInput('credit_card_number'); ?></li>				
				
				<li><?php echo $this->form->getLabel('credit_card_first_name'); ?>
				<?php echo $this->form->getInput('credit_card_first_name'); ?></li>				
				
				<li><?php echo $this->form->getLabel('credit_card_last_name'); ?>
				<?php echo $this->form->getInput('credit_card_last_name'); ?></li>				
				
				<li><?php echo $this->form->getLabel('credit_card_month'); ?>
				<?php echo $this->form->getInput('credit_card_month'); ?></li>				
				
				<li><?php echo $this->form->getLabel('credit_card_year'); ?>
				<?php echo $this->form->getInput('credit_card_year'); ?></li>				
				
				<li><?php echo $this->form->getLabel('credit_card_verification_value'); ?>
				<?php echo $this->form->getInput('credit_card_verification_value'); ?></li>				
				
				<li><?php echo $this->form->getLabel('billing_address_address'); ?>
				<?php echo $this->form->getInput('billing_address_address'); ?></li>				
				
				<li><?php echo $this->form->getLabel('billing_address_zip'); ?>
				<?php echo $this->form->getInput('billing_address_zip'); ?></li>				
				
				<li><?php echo $this->form->getLabel('neighborhood_ids'); ?>
				<?php echo $this->form->getInput('neighborhood_ids'); ?></li>
				
				<li><?php echo $this->form->getLabel('state'); ?>
				<?php echo $this->form->getInput('state'); ?></li>

				<li><?php echo $this->form->getLabel('id'); ?>
				<?php echo $this->form->getInput('id'); ?></li>
			</ul>
			<div class="clr"> </div>
			<?php echo $this->form->getLabel('broker_bio'); ?>
			<div class="clr"> </div>
			<?php echo $this->form->getInput('broker_bio'); ?>
		</fieldset>
	</div>

<div class="width-40 fltrt">
	<?php echo JHtml::_('sliders.start','agent-sliders-'.$this->item->id, array('useCookie'=>1)); ?>

	<?php echo JHtml::_('sliders.panel',JText::_('COM_RENTAL_GROUP_LABEL_PUBLISHING_DETAILS'), 'publishing-details'); ?>
		<fieldset class="panelform">
		<ul class="adminformlist">
			<?php foreach($this->form->getFieldset('publish') as $field): ?>
				<li><?php echo $field->label; ?>
					<?php echo $field->input; ?></li>
			<?php endforeach; ?>
			</ul>
		</fieldset>

	<?php echo JHtml::_('sliders.panel',JText::_('JGLOBAL_FIELDSET_METADATA_OPTIONS'), 'metadata'); ?>
		<fieldset class="panelform">
			<ul class="adminformlist">
				<?php foreach($this->form->getFieldset('metadata') as $field): ?>
					<li><?php echo $field->label; ?>
						<?php echo $field->input; ?></li>
				<?php endforeach; ?>
			</ul>
		</fieldset>

	<?php echo JHtml::_('sliders.end'); ?>
	<input type="hidden" name="task" value="" />
	<?php echo JHtml::_('form.token'); ?>
</div>

<div class="clr"></div>
</form>
