<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');


?>
<div id="form" class="basicModal">
  <div class="h1">Contact Us</div>
  <p class="noMargin">Also check out our <a href="/about/faq">Help/FAQs.</a></p>
  <div id="apartmentNote" class="note hidden"> For all questions about specific apartments, please use the "Contact Now" button on the apartment pages. </div>
  <div class="ajaxUpdateStage">
    <form accept-charset="UTF-8" action="/about/feedback_confirmation" class="new_feedback" data-remote="true" id="feedbackForm" method="post">
      <div style="margin:0;padding:0;display:inline">
        <input name="utf8" type="hidden" value="&#x2713;" />
        <input name="authenticity_token" type="hidden" value="kL5H/rwTqUr+/YrpZvnp3XjwGkEEW5vB2TUGUgwFebw=" />
      </div>
      <div class="padTop15">
        <div class="row">
          <label for="feedback_name">Name</label>
          <input class="idleField" id="feedback_name" name="feedback[name]" size="30" type="text" />
        </div>
        <div class="row">
          <label for="feedback_email">Email</label>
          <input class="idleField" id="feedback_email" name="feedback[email]" size="30" type="text" />
        </div>
        <div class="row">
          <label for="feedback_comment">Comment</label>
          <textarea cols="40" id="comment" name="feedback[comment]" rows="6"></textarea>
        </div>
        <div class="formActions green">
          <input id="location" name="feedback[location]" type="hidden" />
          <a href="#" class="button  submitButton large"><span>Send Message</span></a> </div>
      </div>
    </form>
  </div>
</div>