<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');


?>
<div class="curveTop" id="main">
  <div class="headMessage"> <span class="contactUs">
    <h5>Questions?</h5>
    <a href="/about/faq">Help/FAQs</a> <span class="veryCalm">|</span> <a href="/about/feedback_form" class="feedbackBox cboxElement">Email us</a> | 646-504-2787 </span>
    <h1 class="arial">Features, Pricing and Signup</h1>
    <h2 class="arial">Get started in under two minutes!</h2>
    <div class="clear"></div>
  </div>
  
  <!-- feature block-->
  <div class="sectionTitle"> <span class="calm">~</span> Plan Features <span class="calm">~</span>
    <div class="floatRight"><a class="button white large arrowDown calm" href="#planTable"><span>View Plan Pricing</span></a></div>
  </div>
  <div class="clearfix ui-tabs ui-widget ui-widget-content ui-corner-all" id="features">
    <ul class="ui-helper-reset ui-tabs-nav ui-helper-clearfix ui-widget-header ui-corner-all ui-tabs ui-widget ui-widget-content" id="localNav">
      <li class="first ui-state-default ui-corner-top ui-tabs-selected ui-state-active"><a href="#featuredListings" class=" ">Featured Listings</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#socialSharing">Share on Facebook/Twitter</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#cl" class=" ">Craigslist Templates</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#syndicate" class=" ">Easy Syndication</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#contact" class=" ">Display Contact Info</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#exclusive" class=" ">Exclusive Web Site</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#search" class=" ">Search for Renters</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#sponsor">Neighborhood Sponsorship</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#renters">Quality Renters</a></li>
      <li class="ui-state-default ui-corner-top"><a href="#commitment">No Commitment!</a></li>
    </ul>
    <div class="clearfix" id="content"> 
      <!-- featured listings-->
      <div id="featuredListings" class="ui-tabs-panel ui-widget-content ui-corner-bottom">
        <div class="head">
          <h2>Featured Listings</h2>
          <div class="flags"><a class="planFlag plus" href="#planTable">PLUS</a> <a class="planFlag premium" href="#planTable">Premium</a> plans</div>
        </div>
        <h3>Make your listings stand out in search results by "featuring" them. Just one click in your listings control panel. </h3>
      </div>
      
      <!-- social sharing-->
      <div id="socialSharing" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>Social Sharing</h2>
          <div class="flags"><a class="planFlag all" href="#planTable">all</a> plans</div>
        </div>
        <h3>Share your listings on the major social networks, including <strong>Facebook</strong>, <strong>Twitter</strong> and <strong>LinkedIn</strong> with a single click from your listings control panel.</h3>
      </div>
      
      <!-- craigslist template-->
      <div id="cl" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>Professional Craigslist Templates</h2>
          <div class="flags"><a class="planFlag all" href="#planTable">all</a> plans</div>
        </div>
        <h3>Our professionally-designed templates will make your Craiglist ad stand out from the crowd. Choose the template, copy the code, create the ad and you're done.</h3>
      </div>
      
      <!-- syndicate -->
      <div id="syndicate" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>Easily Syndicate your Listings</h2>
          <div class="flags"><a class="planFlag plus" href="#planTable">PLUS</a> <a class="planFlag premium" href="#planTable">Premium</a> plans</div>
        </div>
        <h3>An optional service that sends your listings beyond Naked Apartments to other leading sites including Zillow, Trulia, Oodle, eBay Classifieds, AOL Real Estate and more. </h3>
      </div>
      
      <!-- contact info-->
      <div id="contact" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>Display  Contact Info</h2>
          <div class="flags"><a class="planFlag plus" href="#planTable">PLUS</a> <a class="planFlag premium" href="#planTable">Premium</a> plans</div>
        </div>
        <h3>Your contact information is prominently displayed to *all* renters.</h3>
        <div class="textBlock first">On <strong>Plus</strong> and <strong>Premium</strong> plans, renters can contact you by calling or emailing you directly.</div>
        <div class="textBlock">On the <strong>Basic</strong> plan, renters need to register before they can contact you.</div>
      </div>
      
      <!-- exclusive web site-->
      <div id="exclusive" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>Exclusive Web Site</h2>
          <div class="flags"><a class="planFlag plus" href="#planTable">PLUS</a> <a class="planFlag premium" href="#planTable">Premium</a> plans</div>
        </div>
        <h3>Your own exclusive site for marketing yourself and all of your listings to potential clients.
          Just your listings - none of your competitors. Use for all your marketing channels.</h3>
      </div>
      
      <!-- search for renters-->
      <div id="search" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>Search for Renters</h2>
          <div class="flags"><a class="planFlag premium" href="#planTable">Premium</a> plan</div>
        </div>
        <h3>Don't wait for renters to find your listings - reach out to those renters looking for apartments that match your listings.</h3>
      </div>
      
      <!-- sponsor a neighborhood-->
      <div id="sponsor" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>Neighborhood Sponsorship</h2>
          <div class="flags"><a class="planFlag premium" href="#planTable">Premium</a> plans</div>
        </div>
        <h3>Get promoted in articles about your neighborhood specialties. We'll place your name, photo, and link to your listings on all available pages.</h3>
      </div>
      
      <!-- sponsor a neighborhood-->
      <div id="renters" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>Quality Renters </h2>
          <div class="flags"><a class="planFlag all" href="#planTable">all</a> plans</div>
        </div>
        <h3>Naked Apartments renters are serious, in-market and dedicated.</h3>
      </div>
      
      <!-- no commitment-->
      <div id="commitment" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">
        <div class="head">
          <h2>No Contracts, No Commitment</h2>
          <div class="flags"><a class="planFlag all" href="#planTable">all</a> plans</div>
        </div>
        <h3>Pay by the month, cancel at anytime - no penalties, no contracts, no problem. </h3>
      </div>
    </div>
  </div>
  <script>na.broker.choosePlan();</script> 
  <a name="planTable"></a>
  <div class="sectionTitle"><span class="calm">~</span> Plan Pricing &amp; Signup <span class="calm">~</span></div>
  <div id="pricingTable">
    <div id="best"><img width="215" height="43" src="/images/home/blank.gif"></div>
    <table id="pricing">
      <thead>
        <tr class="nobg">
          <th class="plan plan1"> <h3><em>♦</em> basic <em>♦</em></h3>
            <h2>$15</h2>
            <h4>/Mo.</h4>
            <h5>A great start!</h5>
          </th>
          <th class="plan plan2 best"> <h3><em>♦</em> plus <em>♦</em></h3>
            <h2>$39</h2>
            <h4>/Mo.</h4>
            <h5>Stand out from the crowd!</h5>
          </th>
          <th class="plan plan3"> <h3><em>♦</em> premium <em>♦</em> </h3>
            <h2>$69</h2>
            <h4>/Mo.</h4>
            <h5>Supercharge your business!</h5>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr target="#popup-unlimited" class="featureTooltip">
          <td class="dark number"><span class="number">20</span> Active Listings</td>
          <td class="dark number pop"><span class="number">50 </span> Active Listings</td>
          <td class="dark number"><span class="number">200 </span> Active Listings</td>
        </tr>
        <tr target="#popup-featured" class="featureTooltip">
          <td class="light number"><span class="number">0 </span> Featured Listings</td>
          <td class="number pop"><span class="number">5 </span> Featured Listings</td>
          <td class="number light"><span class="number">15 </span> Featured Listings</td>
        </tr>
        <tr target="#popup-socialSharing" class="featureTooltip">
          <td class="dark ">Social Sharing</td>
          <td class="dark pop ">Social Sharing</td>
          <td class="dark">Social Sharing</td>
        </tr>
        <tr target="#popup-templates" class="featureTooltip">
          <td class="light">Craigslist Templates</td>
          <td class="pop">Craigslist Templates</td>
          <td class="light">Craigslist Templates</td>
        </tr>
        <tr target="#popup-syndication" class="featureTooltip">
          <td class="dark">&nbsp;</td>
          <td class="dark pop">Easy Syndication</td>
          <td class="dark">Easy Syndication</td>
        </tr>
        <tr target="#popup-InstantContact" class="featureTooltip">
          <td class="light">&nbsp;</td>
          <td class="pop">Display Contact Info</td>
          <td class="light">Display Contact Info</td>
        </tr>
        <tr target="#popup-ignite" class="featureTooltip">
          <td class="dark"></td>
          <td class="dark pop">Exclusive Web Site</td>
          <td class="dark ">Exclusive Web Site</td>
        </tr>
        <tr target="#popup-search" class="featureTooltip">
          <td class="light">&nbsp;</td>
          <td class="pop">&nbsp;</td>
          <td class="light ">Search for Renters</td>
        </tr>
        <tr target="#popup-sponsors" class="featureTooltip">
          <td class="dark">&nbsp;</td>
          <td class="dark pop">&nbsp;</td>
          <td class="dark ">Neighborhood Sponsor</td>
        </tr>
        <tr class="buttons">
          <td class="plan1"><a href="/broker/signup?plan_id=10">&nbsp;</a></td>
          <td rowspan="2" class="plan2 best"><a href="/broker/signup?plan_id=11">&nbsp;</a></td>
          <td class="plan3"><a href="/broker/signup?plan_id=16">&nbsp;</a></td>
        </tr>
        <tr class="extra nobg">
          <td class="blank"></td>
          <td class="blank"></td>
          <td class="blank"></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="hidden">
    <div id="popup-unlimited">
      <h4>Number of Active Listings:</h4>
      Choose between 20, 50 or 200. Easily deactivate old listings to make room for new ones. </div>
    <div id="popup-featured">
      <h4>Make your listings pop!</h4>
      Featured ads are listings highlighted to grab renters' attention.
      <p>And your phone and email are  prominently displayed, enabling renters to contact you instantly. </p>
    </div>
    <div id="popup-socialSharing">
      <h4>Share your listings on Facebook, Twitter and more...</h4>
      An optional service that sends your listings beyond Naked Apartments to other leading sites including <strong>Facebook</strong>, <strong>Twitter</strong> and <strong>LinkedIn</strong> with a single click from your listings control panel.
      <p></p>
    </div>
    <div id="popup-templates">
      <h4>Create Craigslist Templates</h4>
      Our professionally-designed templates will make your Craiglist ad stand out from the crowd. Choose the template, copy the code, create the ad and you're done. </div>
    <div id="popup-syndication">
      <h4>Easily Syndicate your Listings</h4>
      An optional service that sends your listings beyond Naked Apartments to other leading sites including <strong>Zillow</strong>, <strong>Trulia</strong>, <strong>Oodle</strong>, <strong>eBay Classifieds</strong>, <strong>AOL Real Estate</strong> and more. </div>
    <div id="popup-cl">
      <h4>Share your listings on Facebook, Twitter and more...</h4>
      Share your listings on the major social networks, including <strong>Facebook</strong>, <strong>Twitter</strong> and <strong>LinkedIn</strong> with a single click from your listings control panel.
      <p></p>
    </div>
    <div id="popup-InstantContact">
      <h4>Contact info visible to all!</h4>
      Your contact information is prominently displayed to both registered and unregistered renters when they view your listings.
      <p>Since 85% of our traffic is unregistered,  this means many more potential leads for your listings.</p>
    </div>
    <div id="popup-ignite">
      <h4>Create a custom web site</h4>
      Your  own exclusive site for marketing yourself and all of your listings to potential clients.
      <p>Just your listings - none of your competitors. Use for all your marketing channels.</p>
    </div>
    <div id="popup-search">
      <h4>Search for and contact renters!</h4>
      Don't wait for renters to find your listing -  reach out to those renters whose profiles match your listings. Search by apartment size and location, move date, income to find the right match. </div>
    <div id="popup-sponsors">
      <h4>Increase Your Exposure!</h4>
      Get promoted in articles about your neighborhood specialties.
      <p>We'll place your name, photo, and link to your listings on all available pages. </p>
      <p>Placement is rotated among all Premium members. </p>
    </div>
  </div>
  
  <!-- - broker logos - -->
  <div class="contentBlock" id="logosMontage">
    <div class="plug curveBottom"> <em>˜</em> Used by some of NYC's leading RE firms <em>˜</em> </div>
  </div>
  
  <!-- - - FAQ - - -->
  <div id="faq">
    <div class="sectionTitle"> <span class="calm">~</span> Questions and Answers <span class="calm">~</span> </div>
    <div class="column">
      <div class="block">
        <h3>Can I cancel or switch plans at any time?</h3>
        <p>Yes. Only pay from month-to-month and cancel anytime.  Plus, no early termination fees or other obligations. </p>
      </div>
      <div class="block">
        <h3>How do I create listings?</h3>
        <p>You can either manually create your ads using our easy upload form; or, if your company has a listings feed, we can use that to automatically import your listings. (<a href="/about/feedback_form" class="feedbackBox cboxElement">contact us</a> for help with this.)</p>
      </div>
      <div class="block">
        <h3>What are "active" and "inactive" listings</h3>
        <p><strong>Active listings</strong> are those renters can see. The Basic Plan includes 20, the Plus Plan includes 50 and the Premium Plan gives you 200 active listings. </p>
        <p><strong>Inactive listings</strong> are hidden from renters. All plans allow an unlimited number of inactive listings. You can easily switch listings from active to inactive with one click (provided you remain within your plan limits). </p>
      </div>
      <div class="block">
        <h3>What is a Craigslist Template?</h3>
        <p>It's a page template designed to make your listings stand out from the crowd on Craiglist. Simply click a button, copy some text, and paste it into your Craiglist ad. We've got three deluxe templates for you to choose from.</p>
      </div>
      <div class="block"> <span class="floatRight"><a class="planFlag premium" href="#planTable">PREMIUM</a></span>
        <h3>What is a "Neighborhood Sponsor"</h3>
        <p>It means your name, photo and a link to your listings appears at the top of one of our "neighborhood pages", which contain all listings for that neighborhood, as well as a description of the neighborhood. </p>
      </div>
    </div>
    <div class="column last">
      <div class="block"> <span class="floatRight"> <a class="planFlag plus" href="#planTable">plus</a><a class="planFlag premium" href="#planTable" a="">PREMIUM</a> </span>
        <h3>What are "Featured Listings"?</h3>
        <p>They're listings that are highlighted on the search results pages to make them more visible to renters. </p>
      </div>
      <div class="block"> <span class="floatRight"> <a class="planFlag plus" href="#planTable">plus</a><a class="planFlag premium" href="#planTable" a="">PREMIUM</a> </span>
        <h3>What does "Display Contact Info" mean?</h3>
        <p>It means that all renters can instantly view your contact information, regardless of whether they have an account with Naked Apartments. Bottom line, it means more renter traffic.</p>
      </div>
      <div class="block"> <span class="floatRight"><a class="planFlag premium" href="#planTable">PREMIUM</a></span>
        <h3>What does "Renter Search" mean?</h3>
        <p> It means you can search for and contact renters who haven't contacted you. </p>
      </div>
      <div class="block"> <span class="floatRight"> <a class="planFlag plus" href="#planTable">plus</a><a class="planFlag premium" href="#planTable">PREMIUM</a> </span>
        <h3>What's the "Exclusive Web Site"?</h3>
        <p>Your own personal site for displaying all your listings, your bio, your photo, your renter reviews (optional). And no competitor's listings to distract your potential leads.</p>
        <p> Cut and paste the URL into all your marketing materials with the click of a button. </p>
        <p><a class="yellow" target="_blank" href="http://www.nakedapartments.com/me/john-doe">View a demo.</a></p>
        <p></p>
      </div>
      <div class="block">
        <h3>How do I get my listings syndicated?</h3>
        <p>Once you've created your account, just contact us us and we'll start syndicating your listings immediately.</p>
      </div>
    </div>
    <div class="clear"></div>
    <div id="help"> If you have any other questions, call us at <strong>646-504-2787</strong> or <a href="/about/feedback_form" class="feedbackBox cboxElement">Email Us</a>. </div>
  </div>
  <!--close faq --> 
</div>