<?php
/**
 * @version		$Id: apartment.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.helper');

/**
 * Apartment model for the rental component.
 *
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @since		1.6
 */
class RentalModelAjax_Location extends JModel
{
	/**
	 * Gets a list of apartment
	 *
	 * @return	Ajax Location object or false.
	 * @since	1.6
	 */
	function getItems()
	{
		//init vars
		$db			= $this->getDbo();
		$query		= $db->getQuery(true);
		
		$post = JRequest::get('post');
		
		$result = new stdClass();
		
		if (!$post['location_id'])
			return false;
		
		//get sub category
		$query->select('*')
				->from('#__categories')
				->where('extension = "com_rental"')
				->where('parent_id = ' . (int) $post['location_id'])
				->order('title')
			;
			
		$db->setQuery($query);
		$cats = $db->loadObjectList();
		
		$result->sub_category = $cats;
		
		$catid = array();
		
		$catid[] = $post['location_id'];
		
		//get cat id
		foreach ($cats as $cat)
			$catid[] = $cat->id;
		
		$listCatId = implode(',', $catid);
		
		$query		= $db->getQuery(true);
		
		//get location
		$query->select('*')
				->from('#__retal_location')
				->where('catid IN (' . $listCatId . ')')
			;
			
		$db->setQuery($query);
		$locations = $db->loadObjectList();
		
		$result->locations = $locations;
			
		return $result;
	}
}