<?php
/**
 * @version		$Id: apartments.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');
jimport('joomla.application.component.helper');

/**
 * Apartments model for the rental component.
 *
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @since		1.6
 */
class RentalModelApartments extends JModelList
{
	/**
	 * Gets a list of apartments
	 *
	 * @return	array	An array of apartments objects.
	 * @since	1.6
	 */
	function getListQuery()
	{
		$db			= $this->getDbo();
		$query		= $db->getQuery(true);
		
		$query->select(
			'#__rental_apartments.id , #__rental_apartments.bedrooms, #__rental_apartments.price'
		);
		
		$query->from('`#__rental_apartments`');
		
		// Join over the retal_location
$query->select('retal_location_0.title AS retal_location_0_title');
$query->join('INNER', '#__retal_location AS retal_location_0 ON retal_location_0.id = #__rental_apartments.location_id');



		return $query;
	}
}