<?php
/**
 * @version		$Id: favourites.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');
jimport('joomla.application.component.helper');

/**
 * Favourites model for the rental component.
 *
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @since		1.6
 */
class RentalModelFavourites extends JModelList
{
	/**
	 * Gets a list of favourites
	 *
	 * @return	array	An array of favourites objects.
	 * @since	1.6
	 */
	function getListQuery()
	{
		$db			= $this->getDbo();
		$query		= $db->getQuery(true);
		
		$query->select(
			'#__retal_user_favourite_apartments.id , #__retal_user_favourite_apartments.apartment_id'
		);
		
		$query->from('`#__retal_user_favourite_apartments`');
		
		// Join over the users
$query->select('users_0.username AS users_0_username');
$query->join('INNER', '#__users AS users_0 ON users_0.id = #__retal_user_favourite_apartments.user_id');

// Join over the rental_apartments
$query->select('rental_apartments_1.bedrooms AS rental_apartments_1_bedrooms, rental_apartments_1.price AS rental_apartments_1_price');
$query->join('INNER', '#__rental_apartments AS rental_apartments_1 ON rental_apartments_1.id = #__retal_user_favourite_apartments.apartment_id');

// Join over the retal_location
$query->select('retal_location_2.title AS retal_location_2_title');
$query->join('INNER', '#__retal_location AS retal_location_2 ON retal_location_2.id = #__rental_apartments.location_id');



		return $query;
	}
}