<?php
/**
 * @version		$Id: saved.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');
jimport('joomla.application.component.helper');

/**
 * Saved model for the rental component.
 *
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @since		1.6
 */
class RentalModelRenter extends JModel
{
	/**
	 * Check email exist.
	 * @param String $email
	 * @return True if email exist, false if not exist
	 */
	function checkEmailExist($email)
	{
		$db = JFactory::getDbo();
		$query = $db->getQuery(true);
		
		$query->select('*')
				->from('#__users')
				->where('email = "'.$email.'"');
		;
		
		$db->setQuery($query);
		$obj = $db->loadObject();
		
		if ($db->getErrorMsg())
			die($db->getErrorMsg());
		
		if (isset($obj->email))
			return true;
		
		return false;
	}
	
	function getNeighborhood()
	{
		//get in categories
		$db = JFactory::getDbo();
		$query = $db->getQuery(true);
		
		$query->select('*')
				->from('#__categories')
				->where('published = 1')
				->where('extension = "com_rental"')
				->where('parent_id = 1')
		;
		
		$db->setQuery($query);
		$categories = $db->loadObjectList();
		
		foreach ($categories as & $cat)
		{
			//select location
			$query = $db->getQuery(true);
			
			$query->select('*')
					->from('#__retal_location')
					->where('catid = ' . (int) $cat->id . ' OR catid IN (SELECT id FROM #__categories WHERE parent_id = '. (int) $cat->id .')')
			;
			
			#echo str_replace('#__', 'jos_', $query);
			
			$db->setQuery($query);
			$cat->locations = $db->loadObjectList();
		}
		
		return $categories;
	}
}