<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;
?>

<h1>User Profile</h1>

<div>Messages from landlords & brokers</div>

<div>Review the brokers you've worked with!</div>

<div>
	<div>Suggested Apartments</div>
	<div>Favorite Apartments</div>
</div>