<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

//get item
$item = $this->item;
?>

<ul class="item">
	
			<li>
			<?php echo '<label>bedrooms</label>: '. $this->escape($item->bedrooms); ?>
			</li>
			<li>
			<?php echo '<label>bathrooms</label>: '. $this->escape($item->bathrooms); ?>
			</li>
			<li>
			<?php echo '<label>square_ft</label>: '. $this->escape($item->square_ft); ?>
			</li>
			<li>
			<?php echo '<label>listed_for</label>: '. $this->escape($item->listed_for); ?>
			</li>
			<li>
			<?php echo '<label>available_on</label>: '. $this->escape($item->available_on); ?>
			</li>
			<li>
			<?php echo '<label>description</label>: '. $this->escape($item->description); ?>
			</li>
			<li>
			<?php echo '<label>address</label>: '. $this->escape($item->address); ?>
			</li>
			<li>
			<?php echo '<label>address_2</label>: '. $this->escape($item->address_2); ?>
			</li>
			<li>
			<?php echo '<label>city</label>: '. $this->escape($item->city); ?>
			</li>
			<li>
			<?php echo '<label>portal_code</label>: '. $this->escape($item->portal_code); ?>
			</li>
			<li>
			<?php echo '<label>country</label>: '. $this->escape($item->country); ?>
			</li>
			<li>
			<?php echo '<label>price</label>: '. $this->escape($item->price); ?>
			</li>
			<li>
			<?php echo '<label>Amenities</label>: '. $this->escape($item->amenities); ?>
			</li>
</ul>

<!-- gallery images -->

Gallery
<br>
<?php foreach ($item->list_images as $img): ?>
	<img src="<?php echo JURI::base() . 'images/com_rental/upload/' . $img['image']; ?>" width="100" />
<?php endforeach; ?>

<br>

Floor Plan
<br>
<!-- floor plan -->
<?php foreach ($item->list_floor_plan as $img): ?>
	<img src="<?php echo JURI::base() . 'images/com_rental/upload/' . $img['image']; ?>" width="100" />
<?php endforeach; ?>