<?php
/**
 * version $Id: view.html.php $
 * @package		Joomla.Site
 * @subpackage	com_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die;

jimport('joomla.application.component.view');

/**
 * HTML View class for the Content component
 *
 * @package		Joomla.Site
 * @subpackage	com_content
 * @since 1.5
 */

class RentalViewRenter extends JView
{
	protected $items;
	protected $pagination;

	function display($tpl = null)
	{

		// Check for errors.
		if (count($errors = $this->get('Errors'))) {
			JError::raiseError(500, implode("\n", $errors));
			return false;
		}

		$this->_prepareDocument();
		
		// Get the document object.
		$document =& JFactory::getDocument();
		
		// Set the MIME type for JSON output.
		$document->setMimeEncoding('text/javascript');
		
		// Change the suggested filename.
		//JResponse::setHeader('Content-Disposition','attachment;filename="'.$view->getName().'.json"');
		//JResponse::setHeader('');
		header('Content-Type: text/javascript; charset=' . $document->getCharset());
		
		
		
		$current_step = 3;
		
		//get default form
		ob_start();
		echo parent::display($tpl);
		$contents = ob_get_contents();
		ob_end_clean();
		
		switch ($current_step) {
			case 1: //step1 
				$contents = $this->loadTemplate('step1');
				$contents = str_replace('/', '\/', preg_replace('/[\r\n]+/', null, $contents));
				$contents = str_replace('"', '\"', $contents);
				$contents = str_replace("'", "\'", $contents);
				$contents = "$('#new_renter').replaceWith('".$contents."');";
			break;
			case 2:
				$contents = $this->loadTemplate('step2');
			break;
			case 3:
				$contents = $this->loadTemplate('step3');
			break;
			case 4://check form and save data
				
			break;
			
			default:
				;
			break;
		}
		
		
		echo $contents;
		jexit();

		//parent::display($tpl);
	}
	
	/**
	 * Prepares the document
	 */
	protected function _prepareDocument()
	{
		//TODO: prepare document
	}
}
