<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
?>

<?php 
if($this->checkErrors) {
	$contents = $this->loadTemplate('step1');
	$contents = str_replace('/', '\/', preg_replace('/[\r\n]+/', null, $contents));
	$contents = str_replace('"', '\"', $contents);
	$contents = str_replace("'", "\'", $contents);
	$contents = "$('#new_renter').replaceWith('".$contents."');";
	echo $contents; ?>
<?php 	
} else {
?>
hide_form_errors();
<?php }; ?>
hide_all_steps();
$('#signup_step_2').show();
$('#step').val('3');
na.renter_step_signup.indicator(2);