<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_rental
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
$Itemid = JRequest::getInt('Itemid');

?>
<div class="clearfix" id="blueBox"> <span class="admin curve">Have an account? <a class="bold" href="index.php?option=com_rental&view=renter&layout=login<?php echo $Itemid?"&Itemid=".$Itemid:''?>">log in</a></span>
  <h1>Sign up through...</h1>
  <div class="bgBlue curve clearfix">
    <div class="block"> <a id="loginBtn" class="button onBlue large" href="index.php?option=com_rental&view=renter&layout=create-profile<?php echo $Itemid?"&Itemid=".$Itemid:''?>"><span>Naked Apartments</span></a>
      <div class="small padLeft5 itals">(takes about a minute to complete)</div>
    </div>
    <div class="block or">or</div>
    <div class="block fb"> 
    	<a class="btnFB" href="https://graph.facebook.com/oauth/authorize?client_id=149838751731831&amp;redirect_uri=https://www.nakedapartments.com/user_sessions/create&amp;scope=email,publish_stream">
    		<span class=" ">facebook</span>
    	</a> 
    </div>
  </div>
  <div class="clear"></div>
  <div class="oops curve3"><a href="index.php?option=com_rental&view=broker&layout=signup">Landlords, Brokers &amp; Agents: Sign Up here</a></div>
</div>